/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.dynamics;

public interface DynamicsConstants{
    String btRigidBodyDataName = "btRigidBodyFloatData";
    String btTypedConstraintDataName = "btTypedConstraintFloatData";
    String btSliderConstraintDataName = "btSliderConstraintData";
    String btPoint2PointConstraintDataName = "btPoint2PointConstraintFloatData";
    String btGeneric6DofConstraintDataName = "btGeneric6DofConstraintData";
    int BT_6DOF_FLAGS_AXIS_SHIFT = 3;
    String btConeTwistConstraintDataName = "btConeTwistConstraintData";
    String btGeneric6DofSpringConstraintDataName = "btGeneric6DofSpringConstraintData";
    String btGeneric6DofSpring2ConstraintDataName = "btGeneric6DofSpring2ConstraintData";
    int BT_6DOF_FLAGS_AXIS_SHIFT2 = 4;
    int _BT_USE_CENTER_LIMIT_ = 1;
    String btHingeConstraintDataName = "btHingeConstraintFloatData";
    String btGearConstraintDataName = "btGearConstraintFloatData";
    String btMultiBodyDataName = "btMultiBodyFloatData";
    String btMultiBodyLinkDataName = "btMultiBodyLinkFloatData";
}
