/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.linearmath;

public interface LinearMathConstants{
    int BT_BULLET_VERSION = 287;
    double BT_LARGE_FLOAT = 1e18;
    double BT_ONE = 1.0;
    double BT_ZERO = 0.0;
    double BT_TWO = 2.0;
    double BT_HALF = 0.5;
    String btVector3DataName = "btVector3FloatData";
    String btQuaternionDataName = "btQuaternionFloatData";
    int USE_BANCHLESS = 1;
    int USE_BT_CLOCK = 1;
    int BT_USE_PLACEMENT_NEW = 1;
    int BT_HEADER_LENGTH = 12;
}
