/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.badlogic.gdx.physics.bullet.collision;

public interface CollisionConstants{
    String btQuantizedBvhDataName = "btQuantizedBvhFloatData";
    int MAX_SUBTREE_SIZE_IN_BYTES = 2048;
    int MAX_NUM_PARTS_IN_BITS = 10;
    int USE_OVERLAP_TEST_ON_REMOVES = 1;
    int MAX_PREFERRED_PENETRATION_DIRECTIONS = 10;
    int TRI_INFO_V0V1_CONVEX = 1;
    int TRI_INFO_V1V2_CONVEX = 2;
    int TRI_INFO_V2V0_CONVEX = 4;
    int TRI_INFO_V0V1_SWAP_NORMALB = 8;
    int TRI_INFO_V1V2_SWAP_NORMALB = 16;
    int TRI_INFO_V2V0_SWAP_NORMALB = 32;
    int TEST_INTERNAL_OBJECTS = 1;
    int ACTIVE_TAG = 1;
    int ISLAND_SLEEPING = 2;
    int WANTS_DEACTIVATION = 3;
    int DISABLE_DEACTIVATION = 4;
    int DISABLE_SIMULATION = 5;
    String btCollisionObjectDataName = "btCollisionObjectFloatData";
    int DBVT_IMPL_GENERIC = 0;
    int DBVT_IMPL_SSE = 1;
    int DBVT_USE_TEMPLATE = 0;
    int DBVT_USE_INTRINSIC_SSE = 1;
    int DBVT_USE_MEMMOVE = 1;
    int DBVT_ENABLE_BENCHMARK = 0;
    int DBVT_SELECT_IMPL = 0;
    int DBVT_MERGE_IMPL = 0;
    int DBVT_INT0_IMPL = 0;
    int DBVT_BP_PROFILE = 0;
    int DBVT_BP_PREVENTFALSEUPDATE = 0;
    int DBVT_BP_ACCURATESLEEPING = 0;
    int DBVT_BP_ENABLE_BENCHMARK = 0;
    int USE_PATH_COMPRESSION = 1;
    int STATIC_SIMULATION_ISLAND_OPTIMIZATION = 1;
    int USE_DISPATCH_REGISTRY_ARRAY = 1;
    int MANIFOLD_CACHE_SIZE = 4;
    int NO_VIRTUAL_INTERFACE = 1;
    int VORONOI_SIMPLEX_MAX_VERTS = 5;
    double VORONOI_DEFAULT_EQUAL_VERTEX_THRESHOLD = 0.0001;
    double BOX_PLANE_EPSILON = 0.000001;
    double PLANEDIREPSILON = 0.0000001;
    double PARALELENORMALS = 0.000001;
    int MAX_TRI_CLIPPING = 16;
    int NORMAL_CONTACT_AVERAGE = 1;
    double CONTACT_DIFF_EPSILON = 0.00001;
    int BT_DEFAULT_MAX_POOLS = 16;
    int GIMPACT_VS_PLANE_COLLISION = 1;
    int GIM_ARRAY_GROW_INCREMENT = 2;
    int GIM_ARRAY_GROW_FACTOR = 2;
    int GUINT_BIT_COUNT = 32;
    int GUINT_EXPONENT = 5;
    int GIM_INVALID_HASH = 0xffffffff;
    int GIM_DEFAULT_HASH_TABLE_SIZE = 380;
    int GIM_DEFAULT_HASH_TABLE_NODE_SIZE = 4;
    int GIM_HASH_TABLE_GROW_FACTOR = 2;
    int GIM_MIN_RADIX_SORT_SIZE = 860;
    int GIM_NUM_PRIME = 28;
    double G_PI = 3.14159265358979;
    double G_HALF_PI = 1.5707963;
    double G_TWO_PI = 6.28318530;
    double G_ROOT3 = 1.73205;
    double G_ROOT2 = 1.41421;
    int G_UINT_INFINITY = 0xffffffff;
    int G_SIGN_BITMASK = 0x80000000;
    int kHist = 2048;
    int GJK_MAX_ITERATIONS = 128;
    int EPA_MAX_VERTICES = 64;
    int EPA_MAX_FACES = (64 * 2);
    int EPA_MAX_ITERATIONS = 255;
    double BT_MPR_TOLERANCE = 1E-6;
    int BT_MPR_MAX_ITERATIONS = 1000;
}
